# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fdab0d6ba91abe6a477c0e16d6d000f0"
name = "backorder"
handle = "backorder-7"
application_url = "https://photography-task-reaction-single.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_orders,read_products,write_draft_orders"

[auth]
redirect_urls = ["https://photography-task-reaction-single.trycloudflare.com/auth/callback", "https://photography-task-reaction-single.trycloudflare.com/auth/shopify/callback", "https://photography-task-reaction-single.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
